FROM nginx:1.17.10-alpine
# Bundle up the front end.
COPY ./index.html /usr/share/nginx/html
COPY ./yacht-sails-down.png /usr/share/nginx/html
COPY ./yacht-sails-up.png /usr/share/nginx/html
COPY ./yacht-sails-error.png /usr/share/nginx/html
EXPOSE 80