apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-config
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
  # These are here to demonstrate capturing config
  # values in using the environment features of czctl
  SAMPLE1_KEY: VALUE1
  SAMPLE2_KEY: VALUE2
  SAMPLE_PROJECT_VERSION: "Version Production"
  SAMPLE_PROJECT_API_PORT: "{{ .Values.config.containerPort }}"