apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "core.fullname" . }}-pvc
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce