apiVersion: system.codezero.io/v1alpha1
kind: DevelopmentProfile
metadata:
  name: intercept-core
spec:
  commands:
    - command: Teleport
      params:
        kind: Deployment
        resourceName: sample-project-core
        namespace: sample-project
        exclude:
          - sample-project-frontend
    - command: Intercept
      params:
        remoteService: sample-project-core
        namespace: sample-project
        localPort: 4000
        remotePort: 3000
        resourceName: sample-project-core
        header: "X-C60-INTERCEPT:{{email}}"
